name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: pipelines/GitVersion.yml
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        NUGET_AUTH_TOKEN: ${{ secrets.NuGetAPIKey }}
    - name: Restore dependencies
      run: dotnet restore Blazor.CliTool.sln
    - name: Build
      run: dotnet build --no-restore Blazor.CliTool.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Blazor.CliTool.sln
    - name: Pack
      run: dotnet pack --no-build --no-restore /p:Version ${{ steps.gitversion.outputs.nuGetVersion }} --output-path ./artifacts Blazor.CliTool/Blazor.CliTool.csproj
    - name: Publish
      run: dotnet nuget push ./artifacts/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NuGetAPIKey }}
      
